# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: ESLint
      run: yarn lint
    - name: Test suite
      run: yarn test
    - name: Bundle
      run: yarn build
    - name: Test suite using bundle
      run: TEST_DIST=1 yarn test
    - name: Load bundled code
      run: node -e "const Automerge = require(\"./dist/automerge\")"
