name: Browser tests on Sauce Labs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  browsertest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Bundle
        run: yarn build
      - name: Sauce Connect
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
          scVersion: 4.7.0
      - run: ls -al node_modules
      - name: Run tests
        run: node_modules/karma/bin/karma start karma.sauce.js
