name: Browser tests on Sauce Labs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  browsertest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Bundle
        run: yarn build
      - name: saucectl run
        uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ''
          concurrency: 5
      - name: Run tests
        run: karma start karma.sauce.js
